# base stage
FROM alpine:3.19

RUN set -e; \
    apk --no-cache add \
        nodejs \
        yarn \
        python3 \
        perl \
        perl-file-slurp \
        perl-json;

WORKDIR /app

EXPOSE 3000

ENTRYPOINT [ "yarn" ]
CMD [ "dev" ]
